name: Custom Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        type: string
      favorite_color:
        description: 'Favorite Color'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.get-inputs.outputs.username }}
      favorite_color: ${{ steps.get-inputs.outputs.favorite_color }}
    steps:
      - name: Get Inputs
        id: get-inputs
        run: |
          echo "::set-output name=username::${{ github.event.inputs.username }}"
          echo "::set-output name=favorite_color::${{ github.event.inputs.favorite_color }}"
          
  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      GREETING: ${{ steps.greet.outputs.GREETING }}
    steps:
      - name: Create Greeting
        id: greet
        run: |
          USERNAME=${{ needs.job1.outputs.username }}
          COLOR=${{ needs.job1.outputs.favorite_color }}
          GREETING="Hello, $USERNAME! Your favorite color is $COLOR."
          echo "::set-output name=GREETING::$GREETING"
          
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo Greeting
        run: echo "${{ needs.job2.outputs.GREETING }}"
