name: GitHub Actions Workflow
on:
 workflow_dispatch:
   inputs:
     username:
       description: 'Username'
       required: true
     favorite_color:
       description: 'Favorite Color'
       required: true
jobs:
 job1:
   runs-on: ubuntu-latest
   steps:
     - name: Output Inputs
       run: |
         echo "Username: ${{ github.event.inputs.username }}"
         echo "Favorite Color: ${{ github.event.inputs.favorite_color }}"
 job2:
   needs: job1
   runs-on: ubuntu-latest
   steps:
     - name: Create Greeting Message
       id: greeting
       run: |
         greeting="Hello, ${{ github.event.inputs.username }}! Your favorite color is ${{ github.event.inputs.favorite_color }}."
         echo "::set-output name=GREETING::$greeting"
 job3:
   needs: job2
   runs-on: ubuntu-latest
   steps:
     - name: Echo Greeting
       run: |
         echo "${{ steps.greeting.outputs.GREETING }}"
